# Generated by Django 3.2 on 2021-11-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardsclass',
            name='dtStamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newcustomersclass',
            name='dtStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
