# Generated by Django 3.2 on 2021-11-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211117_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardsclass',
            name='dtStamp',
        ),
        migrations.RemoveField(
            model_name='newcustomersclass',
            name='dtStamp',
        ),
    ]
