# Generated by Django 3.2 on 2021-11-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_jobcardsclass_customername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardsclass',
            name='customerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.newcustomersclass'),
        ),
    ]
