# Generated by Django 3.2 on 2021-11-18 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_jobcardsclass_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardsclass',
            name='customerBase',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='main.newcustomersclass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcardsclass',
            name='customerName',
            field=models.CharField(blank=True, max_length=50, verbose_name='Customer Name'),
        ),
    ]
