# Generated by Django 3.2 on 2021-11-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211118_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardsclass',
            name='customerBase',
        ),
    ]
